[build]
  command = "npm --prefix frontend install && CI=false npm --prefix frontend run build"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm --prefix frontend start"
  targetPort = 3000
  framework = "#custom"
